version: '3.3'

services:
    app:
        image: webdevops/php-nginx:8.1
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
        ports:
            - "8080:80"

    database:
        image: postgres:13-alpine
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 'password'
            POSTGRES_USER: 'application'
            POSTGRES_DB: 'application'
        ports:
            - "8033:5432"

volumes:
    db-data:
