<?php

namespace Tests;

use Dotenv\Dotenv;

use function DI\get;

class HomePageTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->refreshDatabase();
    }

    public function test_home_rout_without_cookie()
    {
        $request = $this->createRequest('GET', '/home');
        $response = $this->app->handle($request);
        $this->assertEquals(301, $response->getStatusCode());
    }

    public function test_home_rout_with_cookie()
    {
        $cookieValues = password_hash('6',PASSWORD_DEFAULT). md5("bottle") . password_hash('testPassword',PASSWORD_DEFAULT);
        $request = $this->createRequest(
            'GET',
            '/home',
            ['HTTP_ACCEPT' => 'application/json'],
            [md5('TestToken') => $cookieValues] //todo Установить значение для куки
        );
        $response = $this->app->handle($request);
        $this->assertEquals(200, $response->getStatusCode());
    }
}
