<?php

namespace Tests;

class LogoutPageTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->refreshDatabase();
    }

    public function test_logout_route_with_cookie()
    {
        $cookie = implode(
            md5("bottle"),
            [
                $this->user->id,
                $this->user->password
            ]
        );
        $request = $this->createRequest(
            'GET',
            '/logout',
            ['HTTP_ACCEPT' => 'application/json'],
            ["ce3186f2076d58949b78858d244c3efe" => $cookie]);
        $response = $this->app->handle($request);
        $this->assertEquals('/', $response->getHeaders()['Location'][0]);
        $this->assertStringContainsStringIgnoringCase('1970', $response->getHeaders()['Set-Cookie'][0]);

    }

    public function test_logout_route_without_cookie()
    {
        $request = $this->createRequest(
            'GET',
            '/logout',
        );
        $response = $this->app->handle($request);
        $this->assertEquals(302, $response->getStatusCode());
    }

}